### ISSUE TITLE
error happens when maven compile

### ISSUE THREAD

**Issue by lytfb2015** [linxin26/kafka-monitor#4]
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /D:/opensource/kafka-monitor-master/src/main/java/co/solinx/kafka/monitor/config/PreConfig.java:[4,48] 程序包com.sun.org.apache.xml.internal.security不存在
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by linxin26** [comment]
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] /D:/opensource/kafka-monitor-master/src/main/java/co/solinx/kafka/monitor/config/PreConfig.java:[4,48] 程序包com.sun.org.apache.xml.internal.security不存在
> [INFO] 1 error
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE

已处理。  谢谢。。。
